CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS users (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), email TEXT NOT NULL UNIQUE, password_hash TEXT NOT NULL, role TEXT NOT NULL DEFAULT 'user', is_active BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
ALTER TABLE users ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE;

CREATE TABLE IF NOT EXISTS user_goals (user_id UUID PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE, calories INTEGER NOT NULL DEFAULT 2000, protein NUMERIC(8,2) NOT NULL DEFAULT 150, carbs NUMERIC(8,2) NOT NULL DEFAULT 200, fat NUMERIC(8,2) NOT NULL DEFAULT 65, fiber NUMERIC(8,2) NOT NULL DEFAULT 25, updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS foods (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE, name TEXT NOT NULL, calories NUMERIC(10,2) NOT NULL DEFAULT 0, protein NUMERIC(10,2) NOT NULL DEFAULT 0, carbs NUMERIC(10,2) NOT NULL DEFAULT 0, fat NUMERIC(10,2) NOT NULL DEFAULT 0, fiber NUMERIC(10,2) NOT NULL DEFAULT 0, serving_size TEXT NOT NULL DEFAULT '1 serving', serving_amount NUMERIC(10,2) NOT NULL DEFAULT 1, serving_unit TEXT NOT NULL DEFAULT 'serving', source TEXT NOT NULL DEFAULT 'custom', created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
ALTER TABLE foods ADD COLUMN IF NOT EXISTS serving_amount NUMERIC(10,2) NOT NULL DEFAULT 1;
ALTER TABLE foods ADD COLUMN IF NOT EXISTS serving_unit TEXT NOT NULL DEFAULT 'serving';
CREATE INDEX IF NOT EXISTS foods_user_id_idx ON foods(user_id);
CREATE TABLE IF NOT EXISTS meals (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE, name TEXT NOT NULL, calories NUMERIC(10,2) NOT NULL DEFAULT 0, protein NUMERIC(10,2) NOT NULL DEFAULT 0, carbs NUMERIC(10,2) NOT NULL DEFAULT 0, fat NUMERIC(10,2) NOT NULL DEFAULT 0, fiber NUMERIC(10,2) NOT NULL DEFAULT 0, foods JSONB NOT NULL DEFAULT '[]'::jsonb, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE INDEX IF NOT EXISTS meals_user_id_idx ON meals(user_id);
CREATE TABLE IF NOT EXISTS log_entries (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE, entry_type TEXT NOT NULL CHECK (entry_type IN ('food','meal')), name TEXT NOT NULL, calories NUMERIC(10,2) NOT NULL DEFAULT 0, protein NUMERIC(10,2) NOT NULL DEFAULT 0, carbs NUMERIC(10,2) NOT NULL DEFAULT 0, fat NUMERIC(10,2) NOT NULL DEFAULT 0, fiber NUMERIC(10,2) NOT NULL DEFAULT 0, foods JSONB, quantity NUMERIC(10,2) NOT NULL DEFAULT 1, consumed_at TIMESTAMPTZ NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
ALTER TABLE log_entries ADD COLUMN IF NOT EXISTS quantity NUMERIC(10,2) NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS log_entries_user_date_idx ON log_entries(user_id, consumed_at DESC);

CREATE TABLE IF NOT EXISTS sessions (token_hash TEXT PRIMARY KEY, user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE, expires_at TIMESTAMPTZ NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE INDEX IF NOT EXISTS sessions_user_id_idx ON sessions(user_id);
CREATE INDEX IF NOT EXISTS sessions_expires_at_idx ON sessions(expires_at);
